language: php
php:
  - 5.5

before_script:
  - composer install --dev

script: vendor/bin/phpunit --configuration phpunit.xml --coverage-clover=coverage.clover tests

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email:
    - info@gorka.io
