language: php
php:
  - 5.5
  - 5.6

cache:
    directories:
        - $HOME/.composer/cache

before_script:
  - phpenv config-add travis.ini
  - composer install --dev

script: vendor/bin/phpspec run -n

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/coverage/spec/coverage.xml

notifications:
  email:
    - info@gorka.io